
build_task:
  container:
    matrix:
      - image: python:3.6-alpine
      - image: python:3.7-alpine
      - image: python:3.8-alpine

  build_script:
    - apk add make
    - make install
    - make test
    - apk add curl
    - make deploy
