container:
  image: python:slim

build_task:
  install_script: pip install -r requirements.txt
  run_script: python main.py
  lint_script: flake8 --statistics *.py
  test_script: coverage run --source=main -m unittest -vb test.py
  report_script: coverage report -m
  deploy_script: zip pack.zip *.py
