
build_task:
  container:
    matrix:
      - image: python:3.6-alpine
      - image: python:3.7-alpine
      - image: python:3.8-alpine

  install_script:
    - pip install -r requirements.txt

  run_script:
    - python main.py

  lint_script:
    - flake8 --statistics *.py

  test_script:
    - coverage run --source=main -m unittest -vb test.py

  report_script:
    - coverage report -m

  deploy_script:
    - apk add zip
    - zip pack.zip *.py
