
build_task:
  container:
    matrix:
      - image: python:3.6-alpine
      - image: python:3.7-alpine
      - image: python:3.8-alpine

  build_script:
    - apk add git
    - apk add make
    - make clone
    - make install
    - make test
