
build_task:
  container:
    matrix:
      - image: python:3.8-slim
      - image: python:3.9-slim

  build_script:
    - pip install -r requirements.txt
    - python -m unittest discover -vb tests/
