os: linux
dist: bionic

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -r requirements.txt

script:
  - python main.py
  - flake8 --statistics *.py
  - coverage run --source=main -m unittest -vb test.py

after_success:
  - coverage report -m

deploy:
  - provider: script
    script: zip pack.zip *.py
    edge: true
