version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build:
    parameters:
      tag:
        type: string

    executor:
      name: python/default
      tag: << parameters.tag >>

    steps:
      - checkout
      - make clone
      - make install
      - make test


workflows:
  version: 2
  build:
    jobs:
      - build:
          tag: '3.6'
      - build:
          tag: '3.7'
      - build:
          tag: '3.8'
