version: 2.1

jobs:
  build:
    parameters:
      image:
        type: string

    docker:
      - image: << parameters.image >>

    steps:
      - checkout
      - run: apk add git
      - run: apk add make
      - run: make clone
      - run: make install
      - run: make test


workflows:
  version: 2
  build:
    jobs:
      - build:
          image: 'python:3.6-alpine'
      - build:
          image: 'python:3.7-alpine'
      - build:
          image: 'python:3.8-alpine'
