version: '2.1'


jobs:
  build:
    parameters:
      image:
        type: string

    docker:
      - image: << parameters.image >>

    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -vb tests/


workflows:
  build:
    jobs:
      - build:
          image: 'cimg:3.9'
      - build:
          image: 'cimg:3.8'
