name: action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: python main.py
      - run: flake8 --statistics *.py
      - run: coverage run --source=main -m unittest -vb test.py
      - run: coverage report -m
      - run: zip pack.zip *.py
